// Generated by uniffi-bindgen-react-native
#include "react-native-ambire-crypto.h"
#include "generated/ambire_crypto.hpp"

namespace ambirecrypto {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeAmbireCrypto::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}