// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-ambire-crypto.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNAmbireCryptoSpec.h"

@interface AmbireCrypto : NSObject <NativeAmbireCryptoSpec>
#else
#import <React/RCTBridgeModule.h>

@interface AmbireCrypto : NSObject <RCTBridgeModule>
#endif

@end